[package]
name = "needs"
description = "Check if given bin(s) are available in the PATH"
version = "0.3.2"
edition = "2021"
authors = ["Noah <noahbuergler@proton.me"]
license = "GPL-3.0-or-later"
repository = "https://github.com/NQMVD/needs"
documentation = "https://docs.rs/needs"
keywords = ["cli"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.5.20", features = ["cargo", "derive"] }
clap-cargo = "0.15.2"
rayon = "1.10.0"
regex = "1.11.0"
termcolor = "1.4.1"
which = { version = "7.0.3", features = ["tracing"] }
tracing = "0.1"
tracing-subscriber = "0.3.0"
anyhow = "1.0.98"
xshell = "0.2.7"
colored = "3.0.0"
beef = "0.5.2"

[profile.dev]
split-debuginfo = "unpacked"
debug = 1
